### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by gaoyx-tech** [smartmobilefactory/EpubReaderAndroid#10]
now，i use your code success by write kotlin support in gradle file , but ,when i test my code , i found oom in androidstudio monitor, and i write some destroy code in onstop funciton, but it still oom,do you have some ways to solve it?thanks!

**Comment by timfreiheit** [comment]
hi,
I'm not aware of a memory leak.
Can you check what reference is leaking? Or I need a sample project in which this can be reproduced.
be aware that an oom does not always imply a memory leak. The Epub can be quite large and could itself need a lot of memory.
