### ISSUE TITLE
Uncompressed ePub?

### ISSUE THREAD

**Issue by voipworld** [smartmobilefactory/EpubReaderAndroid#18]
hello team

is it pocible by any way to keep the uncompressed epub, and get rid of the .epub file?
or caching the allready decompressed epub, and load it in the next opening of the app without redecompressing the file?
i have tryed opening a huge book composed of 35 books inside, taking lot lot lot of times
if you can find a solution i'll donate...!
 i love this sdk, good for blind people... what to say...!

**Comment by timfreiheit** [comment]
Hi,
since the version 0.2.2 possible to load uncompressed epubs by using: ``` Epub.fromFolder(folder) ```.
If you load the load a compressed epub the resulted uncompressed ePub will be cached in the app cache directory for the next load.
I also tried your provided example from http://d.shamela.ws/epubs/072/7289.epub which should be a lot faster now.

**Comment by voipworld** [comment]
woo woo woo!
good news...!
how to add it from gradle bro?
thanks!

**Comment by timfreiheit** [comment]
see the installations section in readme.
add 
```
maven { url "https://jitpack.io" }
```
as a new repository in your root build.gradle

and 
```
compile 'com.github.smartmobilefactory:EpubReaderAndroid:0.2.2'
```
in your apps build.gradle

**Comment by voipworld** [comment]
hello
i done all your suggestions
all is 100% working even without uncompressed epub, will try the folder 
caching was not working befaure, now its pretty fast

how do i know the latest version of the sdk?
thanks!

**Comment by timfreiheit** [comment]
you can find the current releases with their changelogs at https://github.com/smartmobilefactory/EpubReaderAndroid/releases
